deploy:
  provider: firebase
	  token:
    	secure: "$FIREBASE_TOKEN"
  message: "Successful deployment"
#notifications:
#  email:
#    recipients:
#      - one@example.com
#      - other@example.com
#    on_success: never # default: change
#    on_failure: always # default: always
